# Generated by Django 4.2.3 on 2023-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinboard',
            name='hoby',
            field=models.TextField(null=True),
        ),
    ]
