# Generated by Django 4.2.3 on 2023-07-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_bulletinboard_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyara', models.CharField(max_length=200)),
                ('slugnum', models.SlugField()),
            ],
        ),
    ]
