# Generated by Django 4.2.3 on 2023-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_secondboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondboard',
            name='likefood',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondboard',
            name='myhoby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
