# Generated by Django 4.2.3 on 2023-07-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_slugnum_secondboard_slugdayo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinboard',
            old_name='slugnum',
            new_name='slug',
        ),
    ]
