# Generated by Django 4.2.3 on 2023-07-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_memberdata_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdata',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='password',
            field=models.SlugField(null=True),
        ),
    ]
