# Generated by Django 4.2.3 on 2023-07-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_rename_user_memberdata_username_memberdata_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdata',
            old_name='password',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='memberdata',
            old_name='username',
            new_name='user',
        ),
    ]
