# Generated by Django 4.2.3 on 2023-07-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='slug',
        ),
    ]
