# Generated by Django 4.2.3 on 2023-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_memberdata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
