# Generated by Django 4.2.3 on 2023-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_alter_commentdata_user_alter_memberdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
