# Generated by Django 4.2.3 on 2023-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_alter_commentdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
