# Generated by Django 4.2.3 on 2023-07-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_memberdata_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='body',
        ),
    ]
