# Generated by Django 4.2.3 on 2023-07-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0022_alter_commentdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
