# Generated by Django 4.2.3 on 2023-08-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_alter_commentdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
