# Generated by Django 4.2.3 on 2023-08-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_alter_commentdata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberData',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
