# Generated by Django 4.2.3 on 2023-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_self_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_introduction',
            name='body',
            field=models.TextField(default='自己紹介してくだせぇ'),
        ),
    ]
