# Generated by Django 4.2.3 on 2023-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_likedbool_remove_commentdata_like_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedbool',
            name='tweet',
            field=models.IntegerField(default=0),
        ),
    ]
