# Generated by Django 4.2.3 on 2023-08-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_alter_likedbool_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='good_bool',
            field=models.BooleanField(default=False),
        ),
    ]
