# Generated by Django 4.2.3 on 2023-08-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_resultmodel_personmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='is_clever',
        ),
        migrations.DeleteModel(
            name='ResultModel',
        ),
        migrations.DeleteModel(
            name='PersonModel',
        ),
    ]
