# Generated by Django 4.2.3 on 2023-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0038_alter_dm_strage_time_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_strage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
