# Generated by Django 4.2.3 on 2023-08-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_image_strage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_strage',
            old_name='name',
            new_name='kyara',
        ),
    ]
