# Generated by Django 4.2.3 on 2023-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_rename_name_image_strage_kyara'),
    ]

    operations = [
        migrations.AddField(
            model_name='self_introduction',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
