# Generated by Django 4.2.3 on 2023-08-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_self_introduction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_init',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/one.png', upload_to='')),
            ],
        ),
    ]
