# Generated by Django 4.2.3 on 2023-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0042_image_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_init',
            name='image',
            field=models.ImageField(default='one.png', upload_to=''),
        ),
    ]
