# Generated by Django 4.2.3 on 2023-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0050_alter_image_init_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_strage',
            name='image',
            field=models.ImageField(default='one.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='self_introduction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
