# Generated by Django 4.2.3 on 2023-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0052_alter_self_introduction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='user_icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
