# Generated by Django 4.2.3 on 2023-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0053_commentdata_user_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image_init',
        ),
    ]
