# Generated by Django 4.2.3 on 2023-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0054_delete_image_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF_bool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userby', models.CharField(max_length=200)),
                ('be_followed', models.CharField(max_length=200)),
                ('follow_switch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FF_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('followed', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
            ],
        ),
    ]
