# Generated by Django 4.2.3 on 2023-08-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_ff_bool_ff_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ff_bool',
            name='follow_switch',
            field=models.BooleanField(default=True),
        ),
    ]
