# Generated by Django 4.2.3 on 2023-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_alter_ff_bool_follow_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ff_bool',
            name='follow_switch',
            field=models.BooleanField(default=False),
        ),
    ]
